# Generated by Django 5.2.7 on 2025-10-12 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('rut', models.CharField(db_index=True, max_length=10, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Aminoacido',
            fields=[
                ('id', models.AutoField(db_column='idAminoacido', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=45)),
                ('tipo_producto', models.CharField(default='Aminoacido', max_length=20)),
                ('tipo', models.CharField(default='Aminoacido', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(upload_to='productos/aminoacidos')),
                ('imagen_nutricional', models.ImageField(upload_to='productos/aminoacidos/info_nutricional', verbose_name='Imagen Información Nutricional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aminoacido',
                'verbose_name_plural': 'Aminoacidos',
                'db_table': 'aminoacidos',
            },
        ),
        migrations.CreateModel(
            name='Creatina',
            fields=[
                ('id', models.AutoField(db_column='idCreatina', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=45)),
                ('tipo_producto', models.CharField(default='Creatina', max_length=20)),
                ('tipo', models.CharField(default='Creatina', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(upload_to='productos/creatinas')),
                ('imagen_nutricional', models.ImageField(upload_to='productos/creatinas/info_nutricional', verbose_name='Imagen Información Nutricional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Creatina',
                'verbose_name_plural': 'Creatinas',
                'db_table': 'creatinas',
            },
        ),
        migrations.CreateModel(
            name='Proteina',
            fields=[
                ('id', models.AutoField(db_column='idProteina', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=45)),
                ('sabor', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('Whey', 'Whey Protein'), ('Isolate', 'Isolate Protein'), ('Casein', 'Casein Protein')], db_index=True, max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('peso', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(upload_to='productos/proteinas')),
                ('imagen_nutricional', models.ImageField(upload_to='productos/proteinas/info_nutricional', verbose_name='Imagen Información Nutricional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proteína',
                'verbose_name_plural': 'Proteínas',
                'db_table': 'proteinas',
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(db_column='idSnack', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=45)),
                ('sabor', models.CharField(max_length=45)),
                ('tipo_producto', models.CharField(default='Snack', max_length=20)),
                ('tipo', models.CharField(default='Snack', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(upload_to='productos/snacks')),
                ('imagen_nutricional', models.ImageField(upload_to='productos/snacks/info_nutricional', verbose_name='Imagen Información Nutricional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snack',
                'verbose_name_plural': 'Snacks',
                'db_table': 'snacks',
            },
        ),
        migrations.CreateModel(
            name='Vitamina',
            fields=[
                ('id', models.AutoField(db_column='idVitamina', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=45)),
                ('tipo_producto', models.CharField(default='Vitamina', max_length=20)),
                ('tipo', models.CharField(default='Vitamina', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(upload_to='productos/vitaminas')),
                ('imagen_nutricional', models.ImageField(upload_to='productos/vitaminas/info_nutricional', verbose_name='Imagen Información Nutricional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vitamina',
                'verbose_name_plural': 'Vitaminas',
                'db_table': 'vitaminas',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('usuario', models.OneToOneField(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('folio', models.AutoField(db_column='idFolio', primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(db_column='idCliente', limit_choices_to={'is_admin': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.PositiveIntegerField()),
                ('subTotal', models.PositiveIntegerField()),
                ('proteina', models.ForeignKey(blank=True, db_column='idProteina', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proteina')),
                ('snack', models.ForeignKey(blank=True, db_column='idSnack', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.snack')),
                ('venta', models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalles_ventas',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(db_column='idItemCarrito', primary_key=True, serialize=False)),
                ('producto_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.PositiveIntegerField()),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(choices=[('proteina', 'Proteína'), ('snack', 'Snack')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carrito', models.ForeignKey(db_column='idCarrito', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carrito')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'db_table': 'items_carrito',
                'unique_together': {('carrito', 'producto_id', 'tipo')},
            },
        ),
    ]
