# Generated by Django 5.2.7 on 2025-12-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_transaccion',
            field=models.CharField(blank=True, db_column='idTransaccion', max_length=100, null=True),
        ),
    ]
