# Generated by Django 5.2.7 on 2025-10-14 16:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aminoacido',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='aminoacido',
            name='imagen_nutricional',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_nutricional'),
        ),
        migrations.AlterField(
            model_name='creatina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='creatina',
            name='imagen_nutricional',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_nutricional'),
        ),
        migrations.AlterField(
            model_name='proteina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='proteina',
            name='imagen_nutricional',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_nutricional'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='imagen_nutricional',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_nutricional'),
        ),
        migrations.AlterField(
            model_name='vitamina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='vitamina',
            name='imagen_nutricional',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_nutricional'),
        ),
    ]
