# Generated by Django 5.2.7 on 2025-10-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_aminoacido_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proteina',
            options={'verbose_name': 'Proteina', 'verbose_name_plural': 'Proteinas'},
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='aminoacido',
            field=models.ForeignKey(blank=True, db_column='idAminoacido', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aminoacido'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='creatina',
            field=models.ForeignKey(blank=True, db_column='idCreatina', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.creatina'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='vitamina',
            field=models.ForeignKey(blank=True, db_column='idVitamina', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vitamina'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='tipo',
            field=models.CharField(choices=[('proteina', 'Proteina'), ('snack', 'Snack'), ('creatina', 'Creatina'), ('aminoacido', 'Aminoacido'), ('vitamina', 'Vitamina')], max_length=20),
        ),
    ]
