# Generated by Django 5.2.7 on 2025-12-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_venta_id_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.venta'),
        ),
    ]
